### ISSUE TITLE
Crap somehow

### ISSUE THREAD

**Issue by Pymann** [tchapi/markdown-cheatsheet#17]
Your cheat-sheet is crap somehow, better use: https://guides.github.com/features/mastering-markdown/

Your stuff is inconsistent with offical doku.

**Comment by mittulmandhan** [comment]
@Pymann If you find something better you can surely suggest it but such behavior must be avoided, not only here, but in the entire community.
I am a contributor to this repository and have been using it for months for documenting my projects. The creation of this repository is intended to help peers.
Please refrain from using such jargon.

**Comment by tchapi** [comment]
Congrats @Pymann for your wonderful 💩 contribution, you have been reported 🥇
